"""Add medical exams

Revision ID: 096617cebce2
Revises: 0001_init
Create Date: 2026-02-19 13:07:45.749137
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '096617cebce2'
down_revision = '0001_init'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medical_exams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('terminal_name', sa.String(length=64), nullable=True),
    sa.Column('result', sa.String(length=32), nullable=False),
    sa.Column('pressure_systolic', sa.Integer(), nullable=True),
    sa.Column('pressure_diastolic', sa.Integer(), nullable=True),
    sa.Column('pulse', sa.Integer(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('alcohol_mg_l', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['minetrack.employees.id'], name=op.f('fk_medical_exams_employee_id_employees')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_medical_exams')),
    schema='minetrack'
    )
    op.create_index(op.f('ix_minetrack_medical_exams_employee_id'), 'medical_exams', ['employee_id'], unique=False, schema='minetrack')
    op.create_index(op.f('ix_minetrack_medical_exams_id'), 'medical_exams', ['id'], unique=False, schema='minetrack')
    op.create_index(op.f('ix_minetrack_medical_exams_timestamp'), 'medical_exams', ['timestamp'], unique=False, schema='minetrack')
    op.drop_constraint(op.f('fk_audit_logs_user_id_users'), 'audit_logs', type_='foreignkey')
    op.create_foreign_key(op.f('fk_audit_logs_user_id_users'), 'audit_logs', 'users', ['user_id'], ['id'], source_schema='minetrack', referent_schema='minetrack')
    op.drop_constraint(op.f('fk_employee_external_ids_employee_id_employees'), 'employee_external_ids', type_='foreignkey')
    op.create_foreign_key(op.f('fk_employee_external_ids_employee_id_employees'), 'employee_external_ids', 'employees', ['employee_id'], ['id'], source_schema='minetrack', referent_schema='minetrack')
    op.drop_constraint(op.f('fk_events_employee_id_employees'), 'events', type_='foreignkey')
    op.drop_constraint(op.f('fk_events_device_id_devices'), 'events', type_='foreignkey')
    op.create_foreign_key(op.f('fk_events_device_id_devices'), 'events', 'devices', ['device_id'], ['id'], source_schema='minetrack', referent_schema='minetrack')
    op.create_foreign_key(op.f('fk_events_employee_id_employees'), 'events', 'employees', ['employee_id'], ['id'], source_schema='minetrack', referent_schema='minetrack')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_events_employee_id_employees'), 'events', schema='minetrack', type_='foreignkey')
    op.drop_constraint(op.f('fk_events_device_id_devices'), 'events', schema='minetrack', type_='foreignkey')
    op.create_foreign_key(op.f('fk_events_device_id_devices'), 'events', 'devices', ['device_id'], ['id'])
    op.create_foreign_key(op.f('fk_events_employee_id_employees'), 'events', 'employees', ['employee_id'], ['id'])
    op.drop_constraint(op.f('fk_employee_external_ids_employee_id_employees'), 'employee_external_ids', schema='minetrack', type_='foreignkey')
    op.create_foreign_key(op.f('fk_employee_external_ids_employee_id_employees'), 'employee_external_ids', 'employees', ['employee_id'], ['id'])
    op.drop_constraint(op.f('fk_audit_logs_user_id_users'), 'audit_logs', schema='minetrack', type_='foreignkey')
    op.create_foreign_key(op.f('fk_audit_logs_user_id_users'), 'audit_logs', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_minetrack_medical_exams_timestamp'), table_name='medical_exams', schema='minetrack')
    op.drop_index(op.f('ix_minetrack_medical_exams_id'), table_name='medical_exams', schema='minetrack')
    op.drop_index(op.f('ix_minetrack_medical_exams_employee_id'), table_name='medical_exams', schema='minetrack')
    op.drop_table('medical_exams', schema='minetrack')
    # ### end Alembic commands ###
