"""add medical_exams table

Revision ID: 2cfc892a8ed4
Revises: 096617cebce2
Create Date: 2026-02-23 13:41:42.694975
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cfc892a8ed4'
down_revision = '096617cebce2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_audit_logs_user_id_users'), 'audit_logs', type_='foreignkey')
    op.create_foreign_key(op.f('fk_audit_logs_user_id_users'), 'audit_logs', 'users', ['user_id'], ['id'], source_schema='minetrack', referent_schema='minetrack')
    op.drop_constraint(op.f('fk_employee_external_ids_employee_id_employees'), 'employee_external_ids', type_='foreignkey')
    op.create_foreign_key(op.f('fk_employee_external_ids_employee_id_employees'), 'employee_external_ids', 'employees', ['employee_id'], ['id'], source_schema='minetrack', referent_schema='minetrack')
    op.drop_constraint(op.f('fk_events_device_id_devices'), 'events', type_='foreignkey')
    op.drop_constraint(op.f('fk_events_employee_id_employees'), 'events', type_='foreignkey')
    op.create_foreign_key(op.f('fk_events_device_id_devices'), 'events', 'devices', ['device_id'], ['id'], source_schema='minetrack', referent_schema='minetrack')
    op.create_foreign_key(op.f('fk_events_employee_id_employees'), 'events', 'employees', ['employee_id'], ['id'], source_schema='minetrack', referent_schema='minetrack')
    op.add_column('medical_exams', sa.Column('esmo_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_minetrack_medical_exams_esmo_id'), 'medical_exams', ['esmo_id'], unique=True, schema='minetrack')
    op.drop_constraint(op.f('fk_medical_exams_employee_id_employees'), 'medical_exams', type_='foreignkey')
    op.create_foreign_key(op.f('fk_medical_exams_employee_id_employees'), 'medical_exams', 'employees', ['employee_id'], ['id'], source_schema='minetrack', referent_schema='minetrack')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_medical_exams_employee_id_employees'), 'medical_exams', schema='minetrack', type_='foreignkey')
    op.create_foreign_key(op.f('fk_medical_exams_employee_id_employees'), 'medical_exams', 'employees', ['employee_id'], ['id'])
    op.drop_index(op.f('ix_minetrack_medical_exams_esmo_id'), table_name='medical_exams', schema='minetrack')
    op.drop_column('medical_exams', 'esmo_id')
    op.drop_constraint(op.f('fk_events_employee_id_employees'), 'events', schema='minetrack', type_='foreignkey')
    op.drop_constraint(op.f('fk_events_device_id_devices'), 'events', schema='minetrack', type_='foreignkey')
    op.create_foreign_key(op.f('fk_events_employee_id_employees'), 'events', 'employees', ['employee_id'], ['id'])
    op.create_foreign_key(op.f('fk_events_device_id_devices'), 'events', 'devices', ['device_id'], ['id'])
    op.drop_constraint(op.f('fk_employee_external_ids_employee_id_employees'), 'employee_external_ids', schema='minetrack', type_='foreignkey')
    op.create_foreign_key(op.f('fk_employee_external_ids_employee_id_employees'), 'employee_external_ids', 'employees', ['employee_id'], ['id'])
    op.drop_constraint(op.f('fk_audit_logs_user_id_users'), 'audit_logs', schema='minetrack', type_='foreignkey')
    op.create_foreign_key(op.f('fk_audit_logs_user_id_users'), 'audit_logs', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
